In [ ]:
import pandas as pd

# Woking with JSON

In [6]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.0389
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.6820
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.8810
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,3.9000
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,2.5300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.1750
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.1910
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.2840
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-06-27,1782518402,0.2840

# Working with SQL

In [15]:
!pip install pyodbc

Requirement already satisfied: pyodbc in e:\anacondasetup\lib\site-packages (5.3.0)

In [16]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=LAPTOP-NRNK8TUB;"
    "DATABASE=MOM;"
    "Trusted_Connection=yes;"
)

print("Connected")

Connected

In [19]:
df = pd.read_sql("SELECT * FROM MOM_Meetings",conn)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17388\2121225137.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM MOM_Meetings",conn)

In [20]:
df

,MeetingID,MeetingDate,MeetingVenueID,MeetingTypeID,DepartmentID,MeetingDescription,DocumentPath,Created,Modified,IsCancelled,CancellationDateTime,CancellationReason
0,1,2024-06-01 10:00:00.000,2,2,2,Faculty meeting on academic planning,docs/faculty_meeting.pdf,2025-12-28 15:34:41.707,2025-12-28 15:34:41.707,False,NaT,None
1,3,2024-06-10 00:00:00.000,4,4,3,Student council discussion on events,docs/student_council.pdf,2025-12-28 15:34:41.707,2026-03-31 12:58:46.027,True,2026-03-31 12:58:46.027,Due to rain
2,4,2024-06-15 00:00:00.000,5,5,5,Exam,docs/exam_committee.pdf,2025-12-28 15:34:41.707,2026-04-01 21:10:37.020,False,NaT,None
3,8,2026-03-04 20:41:59.677,3,4,4,None,/Documents/b5e3fa8a-c403-4ec1-98c5-0c777f2f9fa...,2026-03-04 20:41:59.677,2026-03-16 17:26:19.460,False,NaT,None
4,10,2026-03-16 17:35:25.720,6,4,3,None,None,2026-03-16 17:35:25.720,2026-03-16 17:37:10.970,False,NaT,None
5,11,2026-03-20 00:00:00.000,4,6,22,None,None,2026-03-16 17:38:33.833,2026-03-16 17:49:45.753,False,NaT,None
6,14,2026-03-22 00:00:00.000,8,4,3,None,None,2026-03-16 17:48:19.400,2026-03-16 17:48:19.400,False,NaT,None
7,15,2026-03-20 00:00:00.000,3,3,4,None,None,2026-03-16 17:52:42.547,2026-03-20 18:13:54.617,False,NaT,None
8,19,2026-04-01 00:00:00.000,4,18,5,None,None,2026-04-01 21:30:35.713,2026-04-01 21:30:35.713,False,NaT,None
9,20,2026-04-01 00:00:00.000,4,19,6,None,None,2026-04-01 21:31:57.607,2026-04-01 21:31:57.607,False,NaT,None
10,21,2026-04-01 00:00:00.000,6,20,5,None,None,2026-04-01 21:33:18.930,2026-04-01 21:33:18.930,False,NaT,None
11,23,2026-04-01 00:00:00.000,5,22,5,None,None,2026-04-01 21:47:39.793,2026-04-01 21:47:39.793,False,NaT,None
12,24,2026-04-01 00:00:00.000,4,22,5,None,CWH3.png,2026-04-01 21:51:59.647,2026-04-01 21:52:38.160,False,NaT,None
13,25,2026-04-01 00:00:00.000,8,22,6,None,None,2026-04-01 21:59:08.133,2026-04-01 21:59:08.133,False,NaT,None
14,27,2026-04-01 00:00:00.000,8,25,5,None,None,2026-04-01 22:05:14.633,2026-04-01 22:05:14.633,False,NaT,None
15,28,2026-04-01 00:00:00.000,7,26,3,None,CWH.png,2026-04-01 22:05:24.853,2026-04-01 22:05:56.503,False,NaT,None
16,29,2026-04-01 00:00:00.000,3,27,8,None,None,2026-04-01 22:05:36.863,2026-04-03 10:15:10.950,False,NaT,None
17,31,2026-04-03 00:00:00.000,7,27,5,None,None,2026-04-03 09:56:30.020,2026-04-03 09:56:30.020,False,NaT,None