In [1]:
# One-Hot Encoding exists mainly to solve:

# the biggest problem of Label Encoding

# which is:

# FALSE ORDERING
# STEP 1 — First Understand the Problem in Label Encoding

# Suppose:

# Animal
# Dog
# Cat
# Lion

# Label Encoding converts:

# Animal	Encoded
# Cat	     0
# Dog	     1
# Lion	     2
# The Problem ⚠️

# Machine Learning models may think:

# Lion > Dog > Cat

# because:

# 2 > 1 > 0

# But:

# Animals do NOT have mathematical order.

# This creates:

# False Relationship Problem
# SO WHAT IS THE SOLUTION?

# Instead of:

# ONE column with numbers

# we create:

# SEPARATE binary columns for each category

# This is:

# One-Hot Encoding
# CORE IDEA OF ONE-HOT ENCODING ⭐

# For every category:

# Create separate column

# and fill:

# 1 → category exists
# 0 → category absent
# WHY CALLED “ONE-HOT”?

# Because:

# Only ONE column becomes 1 at a time

# Example:

# Animal_Cat	Animal_Dog	Animal_Lion
# 1                 0	       0

# Only one column is “hot” (1).

# Original Data
# Animal
# Dog
# Cat
# Lion
# Dog
# After One-Hot Encoding
# Animal_Cat	Animal_Dog	Animal_Lion
#    0             	1       	0
#    1	            0        	0
#    0	            0          	1
#    0	            1        	0

In [3]:
import pandas as pd

df = pd.DataFrame({"Animal" : ["Dog" , "Cat" , "Lion" , "Dog"]})
print(df)

  Animal
0    Dog
1    Cat
2   Lion
3    Dog

In [4]:
encoded_df = pd.get_dummies(df["Animal"])
print(encoded_df)

     Cat    Dog   Lion
0  False   True  False
1   True  False  False
2  False  False   True
3  False   True  False

In [5]:
# INTERNAL WORKING : 
# Step 1 : Find unique categories:
# Step 2 : Create separate columns
# Step 3 : Fill binary values

In [6]:
# Adding Encoded Columns Back to Original DF
df_encoded = pd.get_dummies(df , columns=["Animal"])
print(df_encoded)

   Animal_Cat  Animal_Dog  Animal_Lion
0       False        True        False
1        True       False        False
2       False       False         True
3       False        True        False

In [7]:
# Multiple Column One-Hot Encoding
df2 = pd.DataFrame({"Animal" : ["Dog" , "Cat" , "Lion" , "Dog"] , "Size" : ["Medium" , "Small" , "Large" , "Medium"]})
print(df2)

  Animal    Size
0    Dog  Medium
1    Cat   Small
2   Lion   Large
3    Dog  Medium

In [9]:
pd.get_dummies(df2 , columns=["Animal" , "Size"])
# print(df_encoded)

   Animal_Cat  Animal_Dog  Animal_Lion  Size_Large  Size_Medium  Size_Small
0       False        True        False       False         True       False
1        True       False        False       False        False        True
2       False       False         True        True        False       False
3       False        True        False       False         True       False

In [13]:
# Prefix Parameter
# Used for cleaner column names.
pd.get_dummies(df2 , columns=["Animal" , "Size"] , prefix="Pet")

   Pet_Cat  Pet_Dog  Pet_Lion  Pet_Large  Pet_Medium  Pet_Small
0    False     True     False      False        True      False
1     True    False     False      False       False       True
2    False    False      True       True       False      False
3    False     True     False      False        True      False

In [15]:
# drop_first=True

# Cat	Dog	Lion
# 1	0	0

# If:

# Cat=0 AND Dog=0

# then automatically:

# Lion must be 1

# Meaning:

# One column is redundant.

# This creates:

# Multicollinearity

# especially in Linear Regression.

# Solution : Drop one dummy column.



pd.get_dummies(
    df,
    columns=["Animal"]
)

   Animal_Cat  Animal_Dog  Animal_Lion
0       False        True        False
1        True       False        False
2       False       False         True
3       False        True        False

In [16]:
pd.get_dummies(
    df,
    columns=["Animal"],
    drop_first=True
)

   Animal_Dog  Animal_Lion
0        True        False
1       False        False
2       False         True
3        True        False

In [18]:
# Dummy Variable Trap

# When dummy columns become:

# perfectly predictable from each other

# Example:

# If Dog=0 and Lion=0
# then Cat MUST be 1

# This creates:

# linear dependency

# Some ML models struggle.

# Solution

# Use:

# drop_first=True

In [19]:
# Handling Missing Values
df3 = pd.DataFrame({
    "Animal": ["Dog", None, "Cat"]
})

print(df3)

  Animal
0    Dog
1   None
2    Cat

In [21]:
pd.get_dummies(df3) # Missing value ignored.

   Animal_Cat  Animal_Dog
0       False        True
1       False       False
2        True       False

In [23]:
pd.get_dummies(df3, dummy_na=True) # Include Missing Values

   Animal_Cat  Animal_Dog  Animal_nan
0       False        True       False
1       False       False        True
2        True       False       False

In [24]:
# Data Types in One-Hot Encoding

# Output usually:

# True/False

# or:

# 0/1

# depending on pandas version.

pd.get_dummies(df, dtype=int)

   Animal_Cat  Animal_Dog  Animal_Lion
0           0           1            0
1           1           0            0
2           0           0            1
3           0           1            0

In [26]:
# Sparse Matrix Concept

# Suppose:

# 10000 categories

# Most values become:

# 0

# This wastes memory.

# Sparse representation stores only:

# important non-zero values
# Example

pd.get_dummies(df, sparse=True)

# Advanced optimization.

   Animal_Cat  Animal_Dog  Animal_Lion
0       False        True        False
1        True       False        False
2       False       False         True
3       False        True        False